# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8f1c943cdeda335f9a96148fc39c8efabba57c236c3f13281e650e1f7a0b657b830dfb401d552feadced8dc5b126a7498ac4d91754c916e55446b25aac5325

test:
  secret_key_base: 1cc7182a5d41ef130446dd59f9ba8305130a0e3bc9598f7177c52837fa2918d8f3f01ebfd7ca8b781a0b73d98c3e82164d3516dbd08c7a49d25c34e2b78abef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
